name: ImageClassifier
options:
  bundleIdPrefix: io.github.izzaldev
  deploymentTarget:
    iOS: "18.0"
packages:
  HotSwiftUI:
    github: johnno1962/HotSwiftUI
    from: 1.2.5
  InjectionLite:
    github: johnno1962/InjectionLite
    branch: main
  onnxruntime-swift-package-manager:
    github: microsoft/onnxruntime-swift-package-manager
    from: 1.24.2
targets:
  ImageClassifier:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources
    dependencies:
      - package: HotSwiftUI
      - package: InjectionLite
      - package: onnxruntime-swift-package-manager
        product: onnxruntime
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.github.izzaldev.imageclassifier
        SWIFT_VERSION: 6.0
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        EMIT_FRONTEND_COMMAND_LINES: YES
      configs:
        debug:
          SWIFT_COMPILATION_MODE: incremental
          OTHER_LDFLAGS:
            - $(inherited)
            - "-Xlinker"
            - "-interposable"
        release:
          SWIFT_COMPILATION_MODE: wholemodule
schemes:
  ImageClassifier:
    build:
      targets:
        ImageClassifier: all
    run:
      environmentVariables:
        INJECTION_DIRECTORIES: $SRCROOT
